repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: no-commit-to-branch
      args: [--branch, DEV, --branch, TEST, --branch, PROD, --branch, master]
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      language_version: python3.6
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.23.1 # The version of cfn-lint to use
    hooks:
    - id: cfn-python-lint
      files: templates/.*\.(json|yml|yaml|template)$
      language_version: python3.6
-   repo: meta
    hooks:
    - id: check-useless-excludes
-   repo: https://github.com/leppikallio/cfn_nag
    rev: v0.4.37
    hooks:
    - id: cfn_nag
      language: ruby
      exclude: >
          (?x)^(
              .pre-commit-config.yaml
          )$
